Repository TEAM-DDIS/be14-4th-DDIS-BE, pull requests merged in 2025-04, with the labels that each got.

#7 [feat] 회원 가입 기능 구현
  DDIS_Project/.gitignore
  DDIS_Project/build.gradle
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/controller/ClientController.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/controller/ex
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/dto/ClientDTO.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/dto/ex
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientService.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ex
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/aggregate/UserEntity.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/aggregate/ex
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/config/AppConfig.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/repository/ClientRepository.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/repository/ex
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/service/ex
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/vo/SignupRequestVO.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/vo/SignupResponseVO.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/infrastructure/service/ex
  DDIS_Project/src/main/java/com/DDIS/security/config/SecurityConfig.java
  DDIS_Project/src/main/resources/application.yml
Labels: ✨ Feat

#10 [feat] 신고 목록 조회 기능 구현
  DDIS_Project/src/main/java/com/DDIS/report/Query/controller/ReportController.java
  DDIS_Project/src/main/java/com/DDIS/report/Query/controller/ex
  DDIS_Project/src/main/java/com/DDIS/report/Query/dao/ex
  DDIS_Project/src/main/java/com/DDIS/report/Query/dto/ReportDTO.java
  DDIS_Project/src/main/java/com/DDIS/report/Query/dto/ex
  DDIS_Project/src/main/java/com/DDIS/report/Query/mapper/ReportMapper.java
  DDIS_Project/src/main/java/com/DDIS/report/Query/service/ReportService.java
  DDIS_Project/src/main/java/com/DDIS/report/Query/service/ReportServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/report/Query/service/ex
  DDIS_Project/src/main/resources/com/DDIS/report/Query/mapper/ReportMapper.xml
Labels: ✨ Feat

#11 [feat] 게시글 조회 기능 구현
  DDIS_Project/.gitignore
  DDIS_Project/src/main/java/com/DDIS/post/Query/controller/PostController.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/controller/ex
  DDIS_Project/src/main/java/com/DDIS/post/Query/dao/ex
  DDIS_Project/src/main/java/com/DDIS/post/Query/dto/PostDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/dto/ex
  DDIS_Project/src/main/java/com/DDIS/post/Query/mapper/PostMapper.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/service/PostService.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/service/PostServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/service/ex
  DDIS_Project/src/main/resources/application.yml
  DDIS_Project/src/main/resources/com/DDIS/post/Query/mapper/PostMapper.xml
  DDIS_Project/src/main/resources/sql/post/post_all_select.sql
Labels: ✨ Feat

#20 [feat] 개인 Todo 조회 기능 구현
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Query/controller/PersonalTodoQueryController.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Query/controller/ex
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Query/dto/PersonalTodoQueryDTO.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Query/dto/ex
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Query/mapper/PersonalTodoMapper.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Query/service/PersonalTodoQueryService.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Query/service/PersonalTodoQueryServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Query/service/ex
  DDIS_Project/src/main/resources/com/DDIS/personalTodo/Query/mapper/PersonalTodoMapper.xml
  DDIS_Project/src/main/resources/sql/personalTodo/personalTodo_all_select.sql
  DDIS_Project/src/main/resources/sql/personalTodo/personalTodo_categoryTodo_select.sql
  DDIS_Project/src/main/resources/sql/personalTodo/personalTodo_dateTodo_select.sql
  DDIS_Project/src/main/resources/sql/personalTodo/personalTodo_doneTodo_select.sql
  DDIS_Project/src/main/resources/sql/personalTodo/personalTodo_notdoneTodo_select.sql
  DDIS_Project/src/main/resources/sql/personalTodo/personalTodo_pinTodo_select.sql
  DDIS_Project/src/main/resources/sql/personalTodo/personalTodo_privateTodo_select.sql
  DDIS_Project/src/main/resources/sql/personalTodo/personalTodo_publicTodo_select.sql
Labels: ✨ Feat

#22 feat: 개인 카테고리 조회 구현
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Query/controller/PersonalCategoryQueryController.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Query/controller/ex
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Query/dto/PersonalCategoryQueryDTO.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Query/dto/ex
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Query/mapper/PersonalCategoryMapper.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Query/service/PersonalCategoryQueryService.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Query/service/PersonalCategoryQueryServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Query/service/ex
  DDIS_Project/src/main/resources/com/DDIS/personalCategory/Query/mapper/PersonalCategoryMapper.xml
  DDIS_Project/src/main/resources/sql/personalCategory/personalCategory_all_select.sql
Labels: ✨ Feat

#17 [feat] 전체 게시글 공개범위 public 조회 구현
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/controller/PostController.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/controller/ex
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/dto/ex
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/service/PostService.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/service/PostServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/service/ex
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/dto/PostCreateDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/dto/PostResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/entity/Client.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/entity/Post.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/entity/PostCategory.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/ex
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/mapper/PostCommandMapper.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/repository/PostRepository.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/repository/ex
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/service/ex
  DDIS_Project/src/main/java/com/DDIS/post/Command/exception/ErrorResponse.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/exception/GlobalExceptionHandler.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/dto/PostDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/service/PostService.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/service/PostServiceImpl.java
  DDIS_Project/src/main/resources/application.yml
  DDIS_Project/src/main/resources/com/DDIS/post/Query/mapper/PostMapper.xml
Labels: ✨ Feat

#28 Feat/sj/share todo room
  .idea/dataSources.xml
  DDIS_Project/build.gradle
  DDIS_Project/src/main/java/com/DDIS/approve/Command/application/controller/ApproveController.java
  DDIS_Project/src/main/java/com/DDIS/approve/Command/application/dto/CreateApproveDTO.java
  DDIS_Project/src/main/java/com/DDIS/approve/Command/application/dto/UpdateApproveStatusDTO.java
  DDIS_Project/src/main/java/com/DDIS/approve/Command/application/service/ApproveService.java
  DDIS_Project/src/main/java/com/DDIS/approve/Command/application/service/ApproveServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/approve/Command/domain/aggregate/Entity/Approve.java
  DDIS_Project/src/main/java/com/DDIS/approve/Command/domain/repository/ApproveRepository.java
  DDIS_Project/src/main/java/com/DDIS/approve/Command/domain/repository/MemberRepository.java
  DDIS_Project/src/main/java/com/DDIS/approve/Command/domain/repository/MemberShareTodoRepository.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/controller/ClientController.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/dto/ClientDTO.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientService.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/config/AppConfig.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/repository/ClientRepository.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/controller/PostController.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/service/PostService.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/service/PostServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/dto/PostResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/entity/Client.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/entity/Post.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/entity/PostCategory.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/mapper/PostCommandMapper.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/repository/PostRepository.java
  DDIS_Project/src/main/java/com/DDIS/security/config/SecurityConfig.java
  DDIS_Project/src/main/java/com/DDIS/security/filter/JwtAuthenticationFilter.java
  DDIS_Project/src/main/java/com/DDIS/security/util/JwtUtil.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/config/Appconfig.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/controller/GptController.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/controller/RoomController.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/dto/CreateShareRoomDTO.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/dto/ResponseCreateRoomDTO.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/dto/SaveShareTodoDTO.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/service/GptService.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/service/GptServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/service/RoomService.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/service/RoomServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/domain/aggregate/Entity/Clients.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/domain/aggregate/Entity/MemberShareTodo.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/domain/aggregate/Entity/Members.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/domain/aggregate/Entity/PostCategory.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/domain/aggregate/Entity/Posts.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/domain/aggregate/Entity/Rooms.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/domain/aggregate/Entity/ShareTodo.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/domain/repository/PostRepository.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/domain/repository/RoomRepository.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/domain/repository/SharetodoRepository.java
  DDIS_Project/src/main/resources/application.yml
Labels: ✨ Feat

#23 [FEAT] 채팅방 구현
  .idea/misc.xml
  DDIS_Project/build.gradle
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/application/controller/ChatRoomController.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/application/controller/ChatRoomLogController.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/application/dto/ChatRoomLogRequestDTO.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/application/dto/ChatRoomLogResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/application/dto/ChatRoomRequestDTO.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/application/dto/ChatRoomResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/application/service/ChatRoomLogService.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/application/service/ChatRoomService.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/config/WebSocketConfig.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/domain/aggregate/entity/ChatRoomEntity.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/domain/aggregate/entity/ChatRoomLogEntity.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/domain/repository/ChatRoomLogRepository.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Command/domain/repository/ChatRoomRepository.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Query/controller/ChatRoomLogQueryController.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Query/controller/ChatRoomQueryController.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Query/dao/ChatRoomLogMapper.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Query/dao/ChatRoomMapper.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Query/dto/ChatRoomLogQueryDTO.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Query/dto/ChatRoomQueryDTO.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Query/service/ChatRoomLogQueryService.java
  DDIS_Project/src/main/java/com/DDIS/chatRoom/Query/service/ChatRoomQueryService.java
  DDIS_Project/src/main/resources/application.yml
  DDIS_Project/src/main/resources/com/DDIS/chatRoom/Query/mapper/ChatRoomLogMapper.xml
  DDIS_Project/src/main/resources/com/DDIS/chatRoom/Query/mapper/ChatRoomMapper.xml
Labels: ✨ Feat

#30 [feat] 팔로잉, 팔로워 목록 조회 기능 구현
  DDIS_Project/src/main/java/com/DDIS/follow/Query/controller/FollowQueryController.java
  DDIS_Project/src/main/java/com/DDIS/follow/Query/controller/ex
  DDIS_Project/src/main/java/com/DDIS/follow/Query/dao/ex
  DDIS_Project/src/main/java/com/DDIS/follow/Query/dto/FollowQueryDTO.java
  DDIS_Project/src/main/java/com/DDIS/follow/Query/dto/ex
  DDIS_Project/src/main/java/com/DDIS/follow/Query/mapper/FollowMapper.java
  DDIS_Project/src/main/java/com/DDIS/follow/Query/service/FollowQueryService.java
  DDIS_Project/src/main/java/com/DDIS/follow/Query/service/FollowQueryServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/follow/Query/service/ex
  DDIS_Project/src/main/resources/com/DDIS/follow/Query/mapper/FollowMapper.xml
Labels: ✨ Feat

#34 [feat] 팔로우, 언팔로우 기능 구현
  DDIS_Project/src/main/java/com/DDIS/follow/Command/application/controller/FollowCommandController.java
  DDIS_Project/src/main/java/com/DDIS/follow/Command/application/controller/ex
  DDIS_Project/src/main/java/com/DDIS/follow/Command/application/dto/FollowCommandDTO.java
  DDIS_Project/src/main/java/com/DDIS/follow/Command/application/dto/ex
  DDIS_Project/src/main/java/com/DDIS/follow/Command/application/service/FollowCommandService.java
  DDIS_Project/src/main/java/com/DDIS/follow/Command/application/service/FollowCommandServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/follow/Command/application/service/ex
  DDIS_Project/src/main/java/com/DDIS/follow/Command/domain/aggregate/FollowEntity.java
  DDIS_Project/src/main/java/com/DDIS/follow/Command/domain/aggregate/ex
  DDIS_Project/src/main/java/com/DDIS/follow/Command/domain/repository/FollowRepository.java
  DDIS_Project/src/main/java/com/DDIS/follow/Command/domain/repository/ex
  DDIS_Project/src/main/java/com/DDIS/follow/Command/domain/service/ex
Labels: ✨ Feat

#36 [feat] 신고 처리 기능 구현
  DDIS_Project/src/main/java/com/DDIS/report/Command/application/service/ReportCommandServiceImpl.java
Labels: ✨ Feat

#40 [refactor] entity 이름 수정
  DDIS_Project/src/main/java/com/DDIS/report/Command/application/service/ReportCommandServiceImpl.java
Labels: 🔧 Refactor

#42 [FEAT] 모집게시글 작성, 수정, 삭제 기능 구현
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/controller/PostController.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/service/PostService.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/service/PostServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/dto/PostCreateRequestDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/dto/PostResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/dto/PostUpdateRequestDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/entity/Post.java
Labels: ✨ Feat

#48 [FEAT] 개인 Todo Command 기능 구현
  DDIS_Project/build.gradle
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/application/controller/PersonalCategoryCommandController.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/application/controller/ex
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/application/dto/PersonalCategoryCreateDTO.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/application/dto/PersonalCategoryUpdateDTO.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/application/dto/ex
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/application/exception/PersonalCategoryExceptionHandler.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/application/service/PersonalCategoryCommandService.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/application/service/PersonalCategoryCommandServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/application/service/ex
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/domain/aggregate/PersonalCategories.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/domain/aggregate/PersonalCategoryColor.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/domain/aggregate/ex
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/domain/repository/PersonalCategoryRepository.java
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Command/domain/repository/ex
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/controller/PersonalTodoController.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/controller/ex
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/dto/ex
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/dto/request/CreateType.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/dto/request/PersonalTodoCreateRequestDTO.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/dto/request/PersonalTodoDeleteRequestDTO.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/dto/request/PersonalTodoUpdateRequestDTO.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/dto/request/RepeatInfo.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/dto/response/PersonalTodoListResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/dto/response/PersonalTodoResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/exception/PersonalTodoExceptionHandler.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/service/PersonalTodoService.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/service/PersonalTodoServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/service/RepeatDateCalculator.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/service/ex
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/domain/aggregate/PersonalTodoDate.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/domain/aggregate/PersonalTodoDateId.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/domain/aggregate/PersonalTodos.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/domain/aggregate/ex
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/domain/repository/PersonalTodoDateRepository.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/domain/repository/PersonalTodoRepository.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/domain/repository/ex
Labels: ✨ Feat

#51 [feat] applicants 모집게시글 신청, 취소 기능 구현
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/application/controller/ApplicantController.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/application/controller/ex
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/application/dto/ex
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/application/service/ApplicantService.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/application/service/ApplicantServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/application/service/ex
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/domain/aggregate/ApplicantEntity.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/domain/aggregate/ApplicantId.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/domain/aggregate/ex
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/domain/repository/ApplicantRepository.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/domain/repository/ex
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/domain/service/ex
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/infrastructure/service/ex
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/entity/Post.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/mapper/PostMapper.java
Labels: ✨ Feat

#49 [feat] 회원, 관리자 권한 로직 구현
  DDIS_Project/HELP.md
  DDIS_Project/build.gradle
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/controller/ClientController.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientService.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/aggregate/ClientRoleEntity.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/aggregate/ClientRoleId.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/aggregate/RoleEntity.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/aggregate/UserEntity.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/config/AppConfig.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/repository/ClientRoleRepository.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/repository/RoleRepository.java
  DDIS_Project/src/main/java/com/DDIS/security/config/SecurityConfig.java
  DDIS_Project/src/main/java/com/DDIS/security/filter/JwtAuthenticationFilter.java
  DDIS_Project/src/main/java/com/DDIS/security/util/JwtUtil.java
Labels: ✨ Feat

#56 [FEAT] 모집게시글별 신청자 조회
  DDIS_Project/.gitignore
  DDIS_Project/build.gradle
  DDIS_Project/src/main/java/com/DDIS/applicant/Query/controller/ApplicantQueryController.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Query/controller/ex
  DDIS_Project/src/main/java/com/DDIS/applicant/Query/dto/ApplicantListResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Query/dto/ApplicantResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Query/dto/ex
  DDIS_Project/src/main/java/com/DDIS/applicant/Query/mapper/ApplicantMapper.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Query/service/ApplicantQueryService.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Query/service/ApplicantQueryServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/applicant/Query/service/ex
  DDIS_Project/src/main/java/com/DDIS/common/config/ModelMapperConfig.java
  DDIS_Project/src/main/java/com/DDIS/post/config/ModelMapperConfig.java
  DDIS_Project/src/main/java/com/DDIS/postCategory/Command/application/controller/PostCategoryController.java
  DDIS_Project/src/main/java/com/DDIS/postCategory/Command/application/service/PostCategoryService.java
  DDIS_Project/src/main/java/com/DDIS/postCategory/Command/application/service/PostCategoryServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/postCategory/Command/application/service/ex
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/config/Appconfig.java
  DDIS_Project/src/main/java/com/DDIS/shareTodo/Command/application/controller/RoomController.java
  DDIS_Project/src/main/resources/com/DDIS/applicant/Query/mapper/ApplicantMapper.xml
Labels: ✨ Feat

#58 [feat] 회원 정보 수정 기능 구현
  DDIS_Project/build.gradle
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/controller/ClientController.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientService.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/aggregate/UserEntity.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/vo/UpdateProfileRequestVO.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/vo/UpdateProfileResponseVO.java
Labels: ✨ Feat

#60 [FEAT] 모집게시글 구분별 조회
  DDIS_Project/src/main/java/com/DDIS/post/Query/controller/PostController.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/dto/AdminPostDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/dto/PublicPostDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/mapper/PostMapper.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/service/PostService.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/service/PostServiceImpl.java
  DDIS_Project/src/main/resources/com/DDIS/post/Query/mapper/PostMapper.xml
Labels: ✨ Feat

#62 [feat] 이메일 인증 로직 구현
  DDIS_Project/build.gradle
  DDIS_Project/src/main/java/com/DDIS/email/EmailController.java
  DDIS_Project/src/main/java/com/DDIS/email/EmailService.java
  DDIS_Project/src/main/java/com/DDIS/email/EmailServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/email/RedisConfig.java
Labels: ✨ Feat

#65 [refactor] 개인 Todo api명 변경
  DDIS_Project/src/main/java/com/DDIS/personalCategory/Query/controller/PersonalCategoryQueryController.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Command/application/controller/PersonalTodoController.java
  DDIS_Project/src/main/java/com/DDIS/personalTodo/Query/controller/PersonalTodoQueryController.java
Labels: 🔧 Refactor

#66 [feat] 회원가입 시 이메일 인증 필요 구현
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/email/EmailServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/email/RedisConfig.java
Labels: ✨ Feat

#70 [feat] 비밀번호 변경 기능 구현
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/controller/ClientController.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientService.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/aggregate/UserEntity.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/repository/ClientRepository.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/vo/PasswordResetRequestVO.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/vo/PasswordResetResponseVO.java
  DDIS_Project/src/main/java/com/DDIS/email/EmailServiceImpl.java
Labels: ✨ Feat

#68 [FEAT] 모집게시글 검색기능 구현
  DDIS_Project/src/main/java/com/DDIS/applicant/Command/application/controller/ApplicantController.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/controller/PostController.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/service/PostService.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/service/PostServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/dto/PostCreateRequestDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/dto/PostResearchDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/dto/PostResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/aggregate/entity/Post.java
  DDIS_Project/src/main/java/com/DDIS/post/Command/domain/repository/PostRepository.java
Labels: ✨ Feat

#76 [FEAT] 모집게시글 모집 마감시 공동 todo방 생성 버튼 활성화 로직 구현
  DDIS_Project/src/main/java/com/DDIS/post/Command/application/service/PostServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/controller/PostController.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/dto/PostCloseResponseDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/dto/PostCreateTodoRoomDTO.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/mapper/PostMapper.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/service/PostService.java
  DDIS_Project/src/main/java/com/DDIS/post/Query/service/PostServiceImpl.java
  DDIS_Project/src/main/resources/com/DDIS/post/Query/mapper/PostMapper.xml
Labels: ✨ Feat

#79 [FEAT] 마이 페이지 조회 기능 구현
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/controller/ClientController.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientService.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/service/ClientServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/config/AppConfig.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/repository/ClientRepository.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/vo/MypageResponseVO.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/vo/PasswordResetRequestVO.java
  DDIS_Project/src/main/java/com/DDIS/security/config/SecurityConfig.java
  DDIS_Project/src/main/java/com/DDIS/security/filter/JwtAuthenticationFilter.java
  DDIS_Project/src/main/java/com/DDIS/security/util/JwtUtil.java
Labels: ✨ Feat

#86 [refactor] mapper 수정
  DDIS_Project/src/main/java/com/DDIS/report/Query/dto/ReportDTO.java
  DDIS_Project/src/main/resources/com/DDIS/report/Query/mapper/ReportMapper.xml
Labels: 🔧 Refactor

#87 [fix] 코드 수정
  DDIS_Project/src/main/java/com/DDIS/email/EmailController.java
  DDIS_Project/src/main/java/com/DDIS/email/EmailServiceImpl.java
Labels: 🔨 Fix, 🔧 Refactor

#89 [feat] CORS 설정
  DDIS_Project/src/main/java/com/DDIS/security/config/CorsConfig.java
Labels: ✨ Feat

#90 [feat] 신고 등록 프론트 연동
  DDIS_Project/src/main/java/com/DDIS/report/Command/application/dto/ReportRegistRequest.java
  DDIS_Project/src/main/java/com/DDIS/report/Command/application/service/ReportCommandServiceImpl.java
  DDIS_Project/src/main/java/com/DDIS/report/Command/domain/aggregate/entity/ReportEntity.java
Labels: ✨ Feat

#92 [fix] 수정
  DDIS_Project/src/main/java/com/DDIS/client/Command/application/controller/ClientController.java
  DDIS_Project/src/main/java/com/DDIS/client/Command/domain/vo/FindIDResponseVO.java
Labels: 🔨 Fix

#93 [feat] 팔로우 api 수정
  DDIS_Project/src/main/java/com/DDIS/follow/Command/application/controller/FollowCommandController.java
  DDIS_Project/src/main/java/com/DDIS/follow/Query/controller/FollowQueryController.java
  DDIS_Project/src/main/java/com/DDIS/follow/Query/service/FollowQueryService.java
  DDIS_Project/src/main/java/com/DDIS/follow/Query/service/FollowQueryServiceImpl.java
Labels: ✨ Feat
